### ISSUE TITLE
Tester feedback: language

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-AppealsMiscellaneousMotion#1]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `appeals court docket number`
language | This page asks about a motion to stay; this form is intended for motions for relief other than a stay.
Other information | 
Variable being sought | `is_first_document`
Package version | `0.0.1`
Maturity target | Level 1 - this needs to be fixed to be equivalent to the blank form
Tester contact info | Paul Tuttle (Appeals Court)

**Comment by miabonardi** [comment]
Resolved.
