### ISSUE TITLE
Tester feedback: enhancement

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-AppealsMiscellaneousMotion#2]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `motion title`
enhancement | Perhaps some examples of titles, e.g.,

Motion for leave to file supplemental appendix

Motion for leave to file sur-reply brief

Motion to compel assembly of the record
Other information | 
Variable being sought | `motion_title`
Package version | `0.0.1`
Maturity target | Level 2 - this needs to be fixed to meet expectations of a basic intake
Tester contact info | Paul Tuttle (Appeals Court)

**Comment by miabonardi** [comment]
Done.
