### ISSUE TITLE
Tester feedback: language

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-AppealsMiscellaneousMotion#3]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `record appendix`
language | This page should not reference just the Housing Court or the trial court.  It may be copy of other things that are attached to the motion.  Also, no attachment may be required, so the language should be changed to permissive:

Do you have any documents that you would like to attach to your motion?
Other information | 
Variable being sought | `has_evidence`
Package version | `0.0.1`
Maturity target | Level 1 - this needs to be fixed to be equivalent to the blank form
Tester contact info | Paul Tuttle (Appeals Court)

**Comment by miabonardi** [comment]
Done.
